# Core lottery parameters
lottery:
  number_pool: 49
  numbers_to_draw: 6
  min_sum: 100
  max_sum: 200

# Data configuration
data:
  historical_path: "data/historical.csv"
  latest_path: "data/latest_draw.csv"
  stats_dir: "data/stats/"
  results_dir: "data/results/"
  has_header: false
  date_format: "%Y-%m-%d"

# Analysis configuration
analysis:
  # Overdue numbers analysis (standard gaps)
  overdue:
    enabled: true
    threshold: 25
    highlight_cold: true
    cold_threshold: 30
  
  # Inter-number gap analysis
  inter_number_gaps:
    enabled: true
    max_avg: 12.0
    max_single: 20
    min_variety: 3
  
  # Number properties
  primes:
    enabled: true
    min_primes: 1
  even_odd:
    enabled: true
    target_ratio: 0.5
    tolerance: 0.2

# Generation rules
generation:
  gap_constraints:
    overdue:
      enabled: true
      min_include: 1
      max_include: 3
    inter_number:
      enabled: true
      max_avg_gap: 10.0
      max_single_gap: 15
  strategies:
    - weighted
    - balanced
    - random

# Display settings
display:
  show_gap_analysis: true
  gaps:
    highlight_large: true
    large_threshold: 15
  overdue:
    show_all: false
    max_display: 5